# Generated by Django 5.0.1 on 2024-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_catagory_category_alter_provider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.provider'),
        ),
    ]
